#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.neobirdkawe >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.neobirdkawe=/luci-static/neobirdkawe
		set luci.main.mediaurlbase=/luci-static/neobirdkawe
		commit luci
	EOF
fi

exit 0
